// USER ACTION TYPES

export const SEND_PARCEL = {
  REQUEST: "SEND_PARCEL_REQUEST",
  SUCCESS: "SEND_PARCEL_SUCCESS",
  FAIL: "SEND_PARCEL_FAIL",
};

export const USER_LOGIN = {
  REQUEST: "USER_LOGIN_REQUEST",
  SUCCESS: "USER_LOGIN_SUCCESS",
  FAIL: "USER_LOGIN_FAIL",
};

export const USER_LOGOUT = {
  REQUEST: "USER_LOGOUT_REQUEST",
  SUCCESS: "USER_LOGOUT_SUCCESS",
  FAIL: "USER_LOGOUT_FAIL",
};

export const VIEW_PARCEL = {
  REQUEST: "VIEW_PARCEL_REQUEST",
  SUCCESS: "VIEW_PARCEL_SUCCESS",
  FAIL: "VIEW_PARCEL_FAIL",
};

export const DELETE_PARCEL = {
  REQUEST: "DELETE_PARCEL_REQUEST",
  SUCCESS: "DELETE_PARCEL_SUCCESS",
  FAIL: "DELETE_PARCEL_FAIL",
};

// export const TRACK_PARCEL = 'TRACK_PARCEL';

export const EDIT_PARCEL = {
  REQUEST: "EDIT_PARCEL_REQUEST",
  SUCCESS: "EDIT_PARCEL_SUCCESS",
  FAIL: "EDIT_PARCEL_FAIL",
};

//LoginAction
