// USER ACTION TYPES

export const SEND_PARCEL = {
    REQUEST: "GET_PARCEL_REQUEST",
    SUCCESS: "GET_PARCEL_SUCCESS",
    FAIL: "GET_PARCEL_FAIL"
}

export const USER_LOGIN = {
    REQUEST: "USER_LOGIN_REQUEST",
    SUCCESS: "USER_LOGIN_SUCCESS",
    FAIL: "USER_LOGIN_FAIL"
}


export const USER_LOGOUT = {
    REQUEST: "USER_LOGOUT_REQUEST",
    SUCCESS: "USER_LOGOUT_SUCCESS",
    FAIL: "USER_LOGOUT_FAIL"
}

export const VIEW_PARCEL = 'VIEW_PARCEL';
export const DELETE_PARCEL = 'DELETE_PARCEL';
export const TRACK_PARCEL = 'TRACK_PARCEL';
export const EDIT_PARCEL = 'EDIT_PARCEL';

//LoginAction